36 more test coverage
MooreMachine/bootleg-raytracer pull request #45
Opened 2021-05-08 20:20 UTC by MooreMachine

2021-05-08 23:31 UTC, sergio-nnz requested changes

2021-05-08 23:31 UTC, sergio-nnz commented on code/include/color.h
> +    for (auto& i : pixel_color.e) {
We could change i to color_channel to be a little bit more descriptive

2021-05-08 23:31 UTC, sergio-nnz commented on code/include/color.h
> +inline void WriteColor(std::ostream &out, Color pixel_color, int samples_per_pixel) {
Inline should be removed since the function is no longer small.

2021-05-08 23:31 UTC, sergio-nnz commented on code/lib/vector3.cpp
> +Vector3 RandomInUnitSphere() {
We should start thinking on how to avoid multiple loops from this method.

2021-05-08 23:31 UTC, sergio-nnz commented on code/tests/unittests/test_color.cpp
> +TEST(ColorTest, WriteColorPoint25Returns128) {
We could rename this test to WriteColorWhenPassingAPixelOutputsColorValue in order to convey the intent of the WriteColorMethod

2021-05-08 23:31 UTC, sergio-nnz commented on code/tests/unittests/test_vector3.cpp
> +TEST(Vector3RandomTest, RandomWhenNoParametersComponentIsMoreThanZeroUpToOOne) {
Maybe we could change the test name to RandomWhenNoParametersReturnsVectorWithValuesFromMoreThanZeroUpToOne

2021-05-08 23:31 UTC, sergio-nnz commented on code/tests/unittests/test_vector3.cpp
> +TEST(Vector3RandomTest, RandomWhenBadMinMaxThrowError) {
We could change this to RandomWhenMinGreaterThanMaxThrowsError

2021-05-08 23:31 UTC, sergio-nnz commented on code/tests/unittests/test_vector3.cpp
> +TEST(Vector3RandomTest, RandomWhenGoodMinMaxThrowNoError) {
We could change this to RandomWhenMinLessThanMaxThrowsNoError

2021-05-08 23:31 UTC, sergio-nnz commented on code/tests/unittests/test_vector3.cpp
> +TEST_P(Vector3RandomTest, RandomWhenMinMaxComponentIsMoreThanMinUpToMax) {
We could change this to RandomWhenPassingMinMaxParametersReturnsVectorWhithinRange

2021-05-08 23:45 UTC, MooreMachine commented on code/lib/vector3.cpp
> +Vector3 RandomInUnitSphere() {
We will have to leave this for later: https://github.com/MooreMachine/bootleg-raytracer/issues/46

2021-05-09 00:02 UTC, sergio-nnz approved these changes
Approve

2021-05-09 00:04 UTC, merged